name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Install dependencies
        run: npm install  

      - name: Build project
        run: npm run build  

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3  

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2  
        with:
          path: dist  

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  
